### ISSUE TITLE
php-lint-all doesn't identify problematic files, only that there were some

### ISSUE THREAD

**Issue by posita** [digitalpulp/pre-commit-php#18]
Config:

```
# .pre-commit-config.yaml
repos:
  - repo: meta
    hooks:
    - id: check-hooks-apply
    - id: check-useless-excludes
  - repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
    - id: php-lint-all
```

Output:

```
% pre-commit run --verbose --all-files
Check hooks apply to the repository......................................Passed
- hook id: check-hooks-apply
- duration: 0.44s
Check for useless excludes...............................................Passed
- hook id: check-useless-excludes
- duration: 0.41s
PHP Syntax Check (Comprehensive).........................................Failed
- hook id: php-lint-all
- duration: 7.74s
- exit code: 1

Begin PHP Linter
Begin PHP Linter
Begin PHP Linter
Begin PHP Linter
Begin PHP Linter
────────────────────────────────────────────────────────────────────────────────
2 PHP Parse error(s) were found!
────────────────────────────────────────────────────────────────────────────────
Begin PHP Linter
Begin PHP Linter
────────────────────────────────────────────────────────────────────────────────
1 PHP Parse error(s) were found!
────────────────────────────────────────────────────────────────────────────────
Begin PHP Linter
```

It seems like it would be much more useful if the source of the errors were listed.
